name: Tesing workflow variables configuration

on:
  workflow_dispatch

env:
  cloud: google-cloud-test

jobs:
  getting-started:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: Run a one-line script
        run: echo "Hello this is ${{ vars.PROJECT_NAME }}"
        env:
          First_Name: Huy

          