name: Testing Context Variables

on:
  workflow_dispatch

env:
  cloud: google-could

jobs:
  test_context_variables:
    runs-on: ubuntu-latest
    steps:
      - name: "Check Context Variable"
        run: |
          echo "Repository name: ${{ github.repository }}"
          echo "Repository name: ${{ github.workflow }}"
          echo "Repository name: ${{ github.triggering_actor }}"
