name: Testing Secret Variables

on:
  workflow_dispatch
env:
  ACTION_STEP_DEBUG: true
jobs:
  test_context_variables:
    runs-on: ubuntu-latest
    steps:
      - name: "Check Secret"
        run: |
          echo "Secret value ${{ secrets.MY_KEY }}"
