name: Tesing workflow variables

on:
    workflow_dispatch

env:
    cloud: google-cloud-test

jobs:
  getting-started:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
    - name: Run a one-line script
      run: echo "$Greeting, world! $First_Name is using $cloud"
      env:
      	First_Name: Huy


